version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gym-management-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-gym_management}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gym-network

  # Opcional: pgAdmin para gerenciar o banco via interface
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gym-management-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gym-management.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - gym-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  gym-network:
    driver: bridge

